### ISSUE TITLE
Add missing become: true

### ISSUE THREAD

**Issue by mrlesmithjr** [mrlesmithjr/ansible-logstash#10]
The following task is missing `become: true` which is causing this task to fail.

```yaml
- name: debian | assigning Pin priority 1001 on APT Preferences
  template:
    src: "etc/apt/preferences.d/logstash.j2"
    dest: "/etc/apt/preferences.d/logstash"
    owner: root
    group: root
    mode: 0644
```
